# Generated by Django 2.2.4 on 2019-08-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20181127_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaddress',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='stores.Store', verbose_name='Store'),
        ),
    ]
